# Generated by Django 5.2.6 on 2025-09-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relecloud", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="slug",
            field=models.SlugField(default="", unique=True),
            preserve_default=False,
        ),
    ]
